export const carSpecs = {
    price: "$1.42M",
    engine: "6.3L V12",
    hybrid: "HY-KERS",
    hp: "950 HP",
    topSpeed: "217+ MPH",
    acceleration: "< 3s (0-60)",
};

export const features = [
    {
        title: "Active Aerodynamics",
        description: "Diffusers and spoilers typically generated by F1 cars.",
    },
    {
        title: "Carbon Fiber Monocoque",
        description: "Hand-laid carbon fiber chassis for maximum rigidity.",
    },
    {
        title: "Hybrid Precision",
        description: "F1-derived HY-KERS system for instant torque.",
    },
];
